
site_name: CUAHSI JupyterHub
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Profile Environments: profiles.md
  - Installing Software: conda.md
  - HydroShare-on-Jupyter: hydroshare_on_jupyter.md
  - User Interface: ui.md
  - FAQ: faq.md
    #  - Examples: examples.md
    #  - Reference: reference.md
    #  - Contributing: contributing.md
  - About: about.md
theme: readthedocs
